# Generated by Django 3.2.9 on 2021-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=30)),
                ('info_patient', models.BooleanField()),
                ('info_molecule', models.BooleanField()),
                ('info_ronapreve', models.BooleanField()),
                ('info_molnupiravir', models.BooleanField()),
                ('info_remdesivir', models.BooleanField()),
                ('info_hydroxychloroquine', models.BooleanField()),
                ('info_colchicine', models.BooleanField()),
                ('info_azithromycine', models.BooleanField()),
                ('info_avigan', models.BooleanField()),
                ('info_anakinra', models.BooleanField()),
                ('info_pfizer', models.BooleanField()),
                ('info_moderna', models.BooleanField()),
                ('info_astrazeneca', models.BooleanField()),
            ],
        ),
    ]
