# Generated by Django 3.2.9 on 2021-11-15 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_alter_paper_paper_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
