# Generated by Django 3.2.9 on 2021-11-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_paper_paper_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_subject',
            field=models.CharField(default='lalal', max_length=30),
            preserve_default=False,
        ),
    ]
