# Generated by Django 3.2.9 on 2021-12-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_paper_paper_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_most_used_words',
            field=models.TextField(default='rien'),
            preserve_default=False,
        ),
    ]
